### ISSUE TITLE
Order book changes

### ISSUE THREAD

**Issue by kellabyte** [sebs/capcoin#4]
I'm a bit confused about what the live trades websocket stream represents. Are those only buys? Also what exchange(s) do these streamed events come from?

Is there a way to get streaming events for these 3 things?

1. Buy order posted to the order book.
2. Sell order posted to the order book.
3. Order (1 or 2 above) fulfilled.

**Comment by sebs** [comment]
pew,  honestly, I am not a coincap  user, I just wrote the software. I will do some resarch though and add documentation. Thank you for the report back!

**Comment by sebs** [comment]
Can you re-iterate teh question [here at coincap](https://github.com/CoinCapDev/CoinCap.io/issues)
