### ISSUE TITLE
CSV output

### ISSUE THREAD

**Issue by sparcusa** [sebs/capcoin#5]
Hello CapCoiners!

I have a request.   Can you please add a --output csv option to all the output commands?    Its pretty difficult to remove the formating charters from the txt output.

That you be much appreciated.

thanks!

**Comment by sebs** [comment]
I reviewed the request and would like not to implement it. I can elp you by pointing you to jq, which seems to have a way to convert to csv if you need it. 

https://programminghistorian.org/lessons/json-and-jq
